### ISSUE TITLE
Always crashes after first move

### ISSUE THREAD

**Issue by Gitoffthelawn** [CorruptedArk/open-chaos-chess#10]
Tried v1.6.1 on Android Nougat device.  Every time after player makes 1st move in solo game, the game crashes.

**Comment by CorruptedArk** [comment]
Thank you for letting me know, I haven't encountered this problem yet. I'll have to test it on Nougat. Did you have a logcat already by chance?

**Comment by CorruptedArk** [comment]
Also which Nougat version? It has two different API versions.

**Comment by Gitoffthelawn** [comment]
You're welcome.  API 24.  Sorry didn't save a logcat,  I gave it 3 tries, then uninstalled.  I'll get that device back in a week or two, if you still need logcat.

**Comment by CorruptedArk** [comment]
Thanks, and that's alright. I'll try to reproduce the crash, and if I can't, I'll get back to you.

**Comment by CorruptedArk** [comment]
The crash is fixed as of commit [2d86a02](https://github.com/CorruptedArk/open-chaos-chess/commit/2d86a02532795ee9106798caea18c1a285d6e682).

**Comment by Gitoffthelawn** [comment]
Thanks.  I took a quick look at the code changes you made.  Why was that API version-dependent?

**Comment by CorruptedArk** [comment]
That's a good question. Honestly, I have no idea.
