### ISSUE TITLE
Why need fine location permission?  Can it be removed?

### ISSUE THREAD

**Issue by Gitoffthelawn** [CorruptedArk/open-chaos-chess#11]
Why does the app need the fine location permission?  Can it be removed?

**Comment by CorruptedArk** [comment]
Good question. No, it cannot be removed without removing multiplayer. It's necessary for using Bluetooth. [Here](https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions) is some further reading on why that is the case.

**Comment by Gitoffthelawn** [comment]
Thanks.  Maybe disclose in the app description in F-Droid and Play Store?

**Comment by Gitoffthelawn** [comment]
Could it possibly only be requested 1st time multiplayer selected?

**Comment by CorruptedArk** [comment]
I can look into that, but none of a user's location information is stored or sent anywhere by this app, so it's not a risk to privacy.

**Comment by Gitoffthelawn** [comment]
Yes, not a privacy risk.  I'm thinking it may help attract more players without worrying them.  Looks like a fun game. :)

**Comment by CorruptedArk** [comment]
That's a good point, thanks for addressing it. And thanks, I hope you enjoy it.

**Comment by Gitoffthelawn** [comment]
Thank you.  Your app is a real clever idea.  I find regular chess a little too stressful and intense for relaxation.  Checkers is more my speed for relaxation. Okay, maybe a little more intense than checkers for relaxation... but just a little. :)
