### ISSUE TITLE
App Stops Responding on New Game Before AI Moves

### ISSUE THREAD

**Issue by codingotaku** [CorruptedArk/open-chaos-chess#12]
##  Description
As the title says, the game stops responding when launching "new game" before the AI starts its move.

### Steps to reproduce

1. Start Solo play
1. Double tap on any chess piece
1. Press on "new game" before the opponent moves

Tested on Android 10

**Comment by CorruptedArk** [comment]
Thank you for letting me know, I haven't encountered this problem yet.

**Comment by ElonSatoshi** [comment]
I can reproduce this issue without even pressing 'new game'.

Although, I just pressed 'new game' while my move was still going through its animation, and the app didn't crash but it 'started a new game' where every piece was a knight. BUT the pawn I had just moved was still on the board! And then the next move I made crashed the app.

**Comment by codingotaku** [comment]
For me the crash happens when pressing "new game" just before the opponent moves not during the animation.

I haven't gone through the code yet, but it as a workaround one could disable the new game button until the move is complete...
or create and call an `endGame()` method to free up variables before launching the new game.

**Comment by CorruptedArk** [comment]
It's a tricky problem because of how multi-threaded the game is and mandatory interactions with the UI thread, but the current solution I started work on is to block new game and back action while the move thread is running.

**Comment by CorruptedArk** [comment]
I believe the root of the problem is the new game button interferes with the animation while it is running on the UI thread. This essentially locks itself in an infinite loop. If I block the button's action during the animation, it should prevent the lock up. Preliminary testing is promising.

**Comment by CorruptedArk** [comment]
Good suggestions, though. Not bad for an offhand guess.

**Comment by CorruptedArk** [comment]
I just reread your first suggestion, and it's basically the approach I'm taking, so very good guess

**Comment by CorruptedArk** [comment]
This issue should now be fixed in v1.6.3
