### ISSUE TITLE
App frequently stops responding when AI moves

### ISSUE THREAD

**Issue by ElonSatoshi** [CorruptedArk/open-chaos-chess#13]
> ## Description
> 
> As the title says, the game stops responding when launching "new game" before the AI starts its move.
> ### Steps to reproduce
> 
>     1. Start Solo play
> 
>     2. Double tap on any chess piece
> 
>     3. ~~Press on "new game" before the opponent moves~~ Be using a Samsung J3 to play the game.
> 
> 
> Tested on Android ~~10~~ 7

It's similar to #12 but I don't even need to press 'new game', the game just crashes when I try to play, making it unplayable. If I'm lucky enough to be able to make a few moves before it crashes, it says "Can't move that, bruh!" at the bottom of the screen after I make a move, and the computer skips a turn!!

**Comment by ElonSatoshi** [comment]
Updating the game to v1.6.2 fixed the issue. It's still a bit slow though, but maybe that's just because my phone sucks.

**Comment by CorruptedArk** [comment]
I'm glad v1.6.2 fixed it, feel free to submit another issue if you run into any other problems. I'm sorry if it's slow, but there's only so much I can do to increase performance. I hope the game is still fun regardless.
