### ISSUE TITLE
Difficulty is too low when playing against computer in bloodthirst mode.

### ISSUE THREAD

**Issue by vi** [CorruptedArk/open-chaos-chess#15]
I win all the time.

I think the bot should at least prefer capturing moves to regular ones.

**Comment by CorruptedArk** [comment]
The bot prefers captures the same way your pieces do in Bloodthirst mode. The choice of piece just isn't biased

**Comment by CorruptedArk** [comment]
It's hard to say if I should make the computer more biased towards attack because I didn't design the game to be particularly difficult. If the computer always tries to attack, the game may become too difficult.

**Comment by vi** [comment]
Just add a checkbox then.

> If the computer always tries to attack, the game may become too difficult.

If it calculates only the next immediate move (without considering a tree of future moves) then I don't expect it to be too difficult (i.e. unrealistic to win against).

**Comment by CorruptedArk** [comment]
That's fair, I did consider that. It's worth testing at least. And the original concept for bloodthirst was more for the player than the computer

**Comment by CorruptedArk** [comment]
The idea was originally suggested in issue #7

**Comment by vi** [comment]
#7 looks like about Bloodthirst mode itself, not about bot performance in that mode.

**Comment by CorruptedArk** [comment]
Yeah, exactly. Bot performance wasn't considered at all at that point, so this issue is additional functionality upon that, which is fine. I appreciate your take on it. I'll probably implement a toggle that makes the computer more aggressive

**Comment by berkaygunduzz** [comment]
> Yeah, exactly. Bot performance wasn't considered at all at that point, so this issue is additional functionality upon that, which is fine. I appreciate your take on it. I'll probably implement a toggle that makes the computer more aggressive

Has computer any algorithm at normal mode? Some like choosing piece that has more possibility to attack? Because it's also easy too for normal mode.

**Comment by CorruptedArk** [comment]
The aggressive toggle will work with or without Bloodthirst active

**Comment by CorruptedArk** [comment]
The feature has been implemented and will be available in the next release.

**Comment by vi** [comment]
Even in the new mode the game is still too easy.

Maybe some handicap setting should be implemented, for example to start without the queen or to give the computer player five free moves in the beginning.
(or ideally just incrementing calculation depth for computer strategy, but that's much trickier to implement)

**Comment by CorruptedArk** [comment]
Incrementing depth is out of the cards, I think. The randomness would take away the option for a conventional chess engine and I'm not interested in writing one. One option could be to make player moves completely random, like in the normal mode, while keeping the computer moves aggressive like in bloodthirst mode. How does that sound?

**Comment by vi** [comment]
> make player moves completely random, like in the normal mode, while keeping the computer moves aggressive like in bloodthirst mode

I expect it to be way unbalanced. The mode can be implemented, but I expect it to be "nightmare" difficulty.

I'd start with just a usual without-queen / without-rooks options. I expect them to be easy to implement.

**Comment by CorruptedArk** [comment]
That is very easy to implement. I think I'll add it into a separate branch and if it feels good enough, I'll merge it into master

**Comment by CorruptedArk** [comment]
And nightmare might be the sweet spot you're looking for. Being able to think about which piece you choose while your opponent has to roll the dice or get forced into capturing gives you a big advantage from the start

**Comment by vi** [comment]
> Incrementing depth is out of the cards, I think. The randomness would take away the option for a conventional chess engine and I'm not interested in writing one.

Would pull requests for a smart computer player still be welcome?

**Comment by CorruptedArk** [comment]
Yes, pull requests for it are welcome

**Comment by CorruptedArk** [comment]
@vi Do you know how to clone and build the project? I implemented the player handicap mode in the handicap branch. Would you like to test it and let me know what you think?

**Comment by vi** [comment]
Checked out "handicap" branch, won the first game: it is now more interesting, not 100% guaranteed win every time.

I expect pawns in Chaos Chess to be more valuable compared to pawns in usual chess, as they provide greater predictability compared to more powerful pieces.

**Comment by CorruptedArk** [comment]
Do you feel like this is a sufficient handicap or do you think it's still too easy? And an all pawns mode could definitely be done too

**Comment by vi** [comment]
Currently it looks appropriate. More modes are always welcome although - a handicap submenu instead of just one checkbox can be appropriate.

**Comment by CorruptedArk** [comment]
I think I'll merge it and publish a release with it then

**Comment by CorruptedArk** [comment]
I believe #37 provides enough difficulty to close this request
