### ISSUE TITLE
Chess pieces flickering/disappearing

### ISSUE THREAD

**Issue by Vulldozer** [CorruptedArk/open-chaos-chess#18]
**Describe the bug**
The chess pieces disappear/flicker when moving

**To Reproduce**
1. Open the app.
First round you will get expected behavior but.
2) Click new game.
Once you start a new game chess pieces will begin to flicker once you move them. It will remain that way until you restary the app.

**Expected behavior**
The chess pieces shouldn't flicker.

**Screenshots**
![edit_20201206_154936.mp4](https://user-images.githubusercontent.com/59207724/101281931-bd1b1900-37da-11eb-9712-c5b9f23ef124.mp4)

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 8
 - OS: 9.0
 - Version: 1.7.0
 - Build Location: CorruptedArk's GitHub release

**Additional context**

**Comment by CorruptedArk** [comment]
Good catch, I didn't notice it prior to release. I was also able to reproduce the issue with the steps you listed. Plus you get bonus points for using bug report issue template
