### ISSUE TITLE
Selections colour change not honoured

### ISSUE THREAD

**Issue by d5xtgr** [CorruptedArk/open-chaos-chess#19]
The settings allow you to change many of the colours used in the app, but the selections colour is ignored and reset upon leaving the activity.  Inspecting settings.txt, the entry remains `FF888888` in uppercase, while all other entries reflect the user's entry and are in lowercase.

It looks to me like there ought to be a corresponding entry like `colorManager.updateColor(ColorManager.SELECTION_COLOR, getColorInt(selectionColorButton));` around line 236 of `SettingsActivity.java`.  **I have not tested** to see if that fixes it, but it seems suspicious to have the selection colour absent from among all the others here.

**Comment by CorruptedArk** [comment]
Good catch, I'll look into it

**Comment by CorruptedArk** [comment]
I just pushed a commit that appears to fix this issue. Your suggestion was a correct part of the fix, but not all of it. Good offhand guess
