### ISSUE TITLE
Correct initial piece positioning

### ISSUE THREAD

**Issue by d5xtgr** [CorruptedArk/open-chaos-chess#20]
At present, the kings start on the d-file and queens on the e-file.  This is the reverse of the standard, which requires the queen to be placed on her own colour (white queen on light square, black queen on dark square), with a light square at the bottom right for each player.  Since the player makes the first move against the computer, his pieces should adopt the white convention with the queen to the *left* of the king from his perspective.

Affected lines look like 1010 to 1016 of `SinglePlayerBoard.java` and 1444 to 1450 of `MultiPlayerBoard.java`.

**Comment by CorruptedArk** [comment]
This is an easy change, it can be implemented in the next update. That said, in multiplayer, both players are on the bottom from their perspective

**Comment by CorruptedArk** [comment]
Queen and king positions swapped as of latest commit
