### ISSUE TITLE
Crash when attempting to join multiplayer match

### ISSUE THREAD

**Issue by colytmp** [CorruptedArk/open-chaos-chess#21]
Crash log: [https://del.dog/pufingingo.txt](https://del.dog/pufingingo.txt)

>java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setChecked(boolean)' on a null object reference stacktrace: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setChecked(boolean)' on a null object reference 	at dev.corruptedark.openchaoschess.MultiPlayerBoard.onPostCreate(Unknown Source:584) 	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1381) 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3321) 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 	at android.os.Handler.dispatchMessage(Handler.java:107) 	at android.os.Looper.loop(Looper.java:214) 	at android.app.ActivityThread.main(ActivityThread.java:7356) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)_

**Comment by CorruptedArk** [comment]
Good catch, will investigate
