### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [CorruptedArk/open-chaos-chess#22]
**Describe the bug**
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 1.7.4 (37), my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

**To Reproduce**
1. use the largest font and display
2. See error

**Expected behavior**
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

**Screenshots**
<img width="474" alt="bug-openchaoschess-2" src="https://user-images.githubusercontent.com/18572115/103228785-929d2580-496c-11eb-9283-8b37bc912557.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Nexus 5]
 - OS: [e.g. Android 9.0] Android 8.0
 - Version: [e.g. 1.6.4]  1.7.4 (37) 
 - Build Location: [e.g. F-Droid release, CorruptedArk's GitHub release/build from source] F-Droid release

**Additional context**

**Comment by CorruptedArk** [comment]
Thanks for bringing this to my attention and thanks for the kind words. As of this moment, I am the only programmer on this project. Would you consider a scrollable view an acceptable solution to this problem? If so, I can fix this very easily

**Comment by CorruptedArk** [comment]
Also bonus points for using and filling out the issue template

**Comment by franklinbill** [comment]
Thanks*3000 for your reply! I think it's a good way to fix it.
