### ISSUE TITLE
Dual player offline (no bluetooth)

### ISSUE THREAD

**Issue by APN-Pucky** [CorruptedArk/open-chaos-chess#23]
I'd love to be play with an human enemy on a single device.

**Comment by CorruptedArk** [comment]
I've given myself time to contemplate my response to this feature request. After long consideration, I've decided I'm not going to implement it. I already sunk a lot of time into Bluetooth multiplayer and I don't feel like it's too much more inconvenient to use that than a single device multiplayer would be. I also understand how much more time and effort it would take to implement single device multiplayer, and I don't think it's worth it.

However, I do deeply appreciate your interest in my game and your willingness to speak up about how you'd like it to be.

While I have no plans to implement this feature, I am open to pull requests if anyone else does.

**Comment by APN-Pucky** [comment]
Thank you for taking the time and considering it.
