### ISSUE TITLE
Add a sound effects option in settings or another way to make moves feel impactful

### ISSUE THREAD

**Issue by Vulldozer** [CorruptedArk/open-chaos-chess#24]
**Is your feature request related to a problem? Please describe.**
Not a problem per say but winning a game or knocking out a enemy peice feels kind of bland, need a way of making the player moves feel like they have more impact.

**Describe the solution you'd like**
Have an option in the settings menu to enable sound effects, preferably when a chess peice gets knocked out or when you lose/win the game.

**Describe alternatives you've considered**
Any other way to make your moves feel like they have an impact. Maybe instead of sound effects you can show the scored points show a little "+1" before incrementing instead of it incrementing the moment you makr the move.

**Additional context**
I couldn't think if specific sound effects but I did make some examples of numbers incrementing
![20210220_111746.jpg](https://user-images.githubusercontent.com/59207724/108590703-98f8be00-736d-11eb-8766-661d9bc4272d.jpg)

**Comment by CorruptedArk** [comment]
I'm not sure when I'll get to this feature request, but I like it and I plan on implementing it. Everything in this request sounds like a good quality of life improvement.

**Comment by CorruptedArk** [comment]
I'm open to suggestions for sound effects in this issue. They need to be compatible with the license of the project.
