### ISSUE TITLE
Increase differentiation between king and bishops

### ISSUE THREAD

**Issue by Gitoffthelawn** [CorruptedArk/open-chaos-chess#29]
The king looks much like the bishops.  Perhaps style the king to further differentiate it from the bishops.

**Comment by CorruptedArk** [comment]
Any mock-ups or more specific suggestions are welcome. This issue is too vague to work from at this point.

**Comment by Vulldozer** [comment]
@CorruptedArk 
I think the bishop should look "carved" kind of like this:
![carvedbishop](https://user-images.githubusercontent.com/59207724/112729898-8f9bdc00-8f3f-11eb-8223-2d19ec24291c.jpg)

A quick edit I made just to give a general idea:
![estimation](https://user-images.githubusercontent.com/59207724/112730103-b3135680-8f40-11eb-9c7e-c8d4e4d47f8c.jpeg)

**Comment by CorruptedArk** [comment]
That's an easy change, I think it's acceptable

**Comment by Gitoffthelawn** [comment]
The queen looks so much larger than the king... do you think in addition to changing the bishop appearance, the king could be increased in size by a small factor, like 5-10%?

BTW, I started playing bloodthirst mode and giving the computer a handicap... I didn't realize what handicap did until I went to move my queen! LOL.  Computer hasn't beaten me yet, but I'm trying to give it every advantage!

**Comment by CorruptedArk** [comment]
Yeah, the king can be increased in size a bit, that's a pretty easy change. And I hope you're enjoying the new mode

**Comment by Gitoffthelawn** [comment]
Thanks! I've always had mixed emotions about chess.  I enjoy the game, but it's not relaxing enough for me.  Chaos chess is a good balance between chess and relaxing! :)

**Comment by CorruptedArk** [comment]
I have reconsidered changing the size of the king, and decided not to do so. The king already fills the complete height of a square, and I do no believe it would look better wider. The only other way to increase its size would be to increase the size of the square itself, and that looks worse rather than better.

**Comment by Gitoffthelawn** [comment]
Sounds good.  I was concerned about those issues, but thought perhaps you found a clever way around them! :)

I haven't had any time to play (anything) lately, so I haven't seen the newer version with the improved bishops yet.
