### ISSUE TITLE
freeze after first move

### ISSUE THREAD

**Issue by ralmcruz** [CorruptedArk/open-chaos-chess#3]
After first move the APP freezes. 

Using a degoogled xiaomi mi a2 lite.

**Comment by CorruptedArk** [comment]
Thanks for submitting this. You're having the problem on the current F-Droid version, right? If so, this is a known problem and should be fixed in the current  release  on this repository. I would appreciate if you're willing to try it out until the F-Droid build catches up.

**Comment by ralmcruz** [comment]
Yes. This release solve the problem.

**Comment by CorruptedArk** [comment]
Alright, thanks for the feedback
