### ISSUE TITLE
Metal music

### ISSUE THREAD

**Issue by KaiFujiro** [CorruptedArk/open-chaos-chess#30]
I have an idea with the music in this game, this game has a name "chaos". Can you just add metal music as music in this game? or some kind of "music loader" that can be added in this game

**Comment by Vulldozer** [comment]
I don't know about you but in my opinion metal music and chess don't go well together.

**Comment by CorruptedArk** [comment]
I agree with Vulldozer on this, adding a music player to this game is far too out of scope. This is not something I plan on implementing
