### ISSUE TITLE
Checkmark colors don't match board color 1

### ISSUE THREAD

**Issue by Vulldozer** [CorruptedArk/open-chaos-chess#33]
**Describe the bug**
The color of the checkmarks in the options menu for "Enable Handicap" option and "Agressive Computer" option don't always match "Board Color 1".

When you change board color 1, the color of the checkmark for "Bloodthirst by default" option changes immeditaly which is expected behavior.

However, the "Agressive Computer" option checkmark retains the previous board color until you reopen the menu.

The "Enable handicap" checkmark color never changes no matter what you do, it will always remain red.

**To Reproduce**
1. Go to settings menu.
2. Change board color 1 to any color.
3. Save colors.
4. See error.

**Expected behavior**
All checkmarks should have the same color as board color 1 immeditaly after the color gers changed.

**Screenshots**
![Screenshot_20210331-113322_Open Chaos Chess.jpg](https://user-images.githubusercontent.com/59207724/113115305-f9a0d380-9214-11eb-9ca1-befb8f6ee564.jpg)

**Smartphone**
 - Device: Samsung Galaxy Note 8
 - OS: Androud 9.0
 - Version: 1.7.9
 - Build Location: F-Droid

**Comment by CorruptedArk** [comment]
Good catch, I did a quick look at the code and I know what's wrong. I'll fix that next time I'm working on it.
