### ISSUE TITLE
Not playable on square screens

### ISSUE THREAD

**Issue by devenblake** [CorruptedArk/open-chaos-chess#34]
On devices with a nearly 1:1 aspect ratio only half of the chess board is viewable.

To reproduce, start the game on a square screen.

**Expected behavior**
It would be cool if the application could adapt to the screen aspect or allow the user to change the size and position of the board manually.

**Screenshots**
![Screenshot_20210407-111940_Open_Chaos_Chess](https://user-images.githubusercontent.com/26193059/113891867-7a227f80-9793-11eb-8cb7-03090e7d9973.png)
![Screenshot_20210407-111946_Open_Chaos_Chess](https://user-images.githubusercontent.com/26193059/113891881-7c84d980-9793-11eb-9fec-974562fa3b8c.png)

**Smartphone:**
 - Device: Unihertz Titan
 - OS: An unofficial build of Lineage OS 17.1 (Android 10 based)
 - Build Location: F-Droid via Aurora Droid. Version 1.7.9.42

**Comment by CorruptedArk** [comment]
Honestly, I didn't think there were any 1:1 Android devices when I first designed the game, so I didn't take it into account. I believe I can solve this with scroll views, but dealing with board square positioning is going to be a headache if I do. I have to think about this one.

**Comment by devenblake** [comment]
I see you made a [commit](https://github.com/CorruptedArk/open-chaos-chess/commit/bdb2dd00dc521183b8fab0e4455597b19a13a9d9) which should fix this! Thank you!

**Comment by CorruptedArk** [comment]
I tweaked the way views are scaled depending on the aspect ratio, it should work for you now and I'd appreciate if you test it on your device and provide feedback
