### ISSUE TITLE
Not playable on some screens

### ISSUE THREAD

**Issue by egorguslyan** [CorruptedArk/open-chaos-chess#38]
After last commit *bdb2dd0* it's hard to play on normal screen.
![Screenshot_20210419-205720_Open_Chaos_Chess](https://user-images.githubusercontent.com/42677093/115282116-54a15880-a139-11eb-9132-7588f6e88dad.png)

**Comment by CorruptedArk** [comment]
Alright, I'll have to figure that one out

**Comment by egorguslyan** [comment]
Works good
![Screenshot_20210420-171535_Open_Chaos_Chess](https://user-images.githubusercontent.com/42677093/115411466-047ed080-a1e3-11eb-8f33-63799fcbefb3.png)

**Comment by egorguslyan** [comment]
But not on the square screens with software navigation buttons
![Screenshot_10](https://user-images.githubusercontent.com/42677093/115413537-c97d9c80-a1e4-11eb-9eff-4afa580f3778.png)

**Comment by egorguslyan** [comment]
I have an attempt to fix it in my fork. It works like this:
![Screenshot_20210420-175441_Open_Chaos_Chess](https://user-images.githubusercontent.com/42677093/115418290-e87e2d80-a1e8-11eb-92f8-0231f02ca241.png)
![Screenshot_11](https://user-images.githubusercontent.com/42677093/115418316-ef0ca500-a1e8-11eb-8784-1de306331544.png)
![Screenshot_12](https://user-images.githubusercontent.com/42677093/115418338-f16eff00-a1e8-11eb-876e-13a2b881c470.png)
![Screenshot_20210420-175305_Open_Chaos_Chess](https://user-images.githubusercontent.com/42677093/115418372-f8960d00-a1e8-11eb-868f-47e7a88f88a1.png)

**Comment by CorruptedArk** [comment]
Your changes seem like a good resolution for this issue, I'm going to merge them and apply them to multiplayer as well

**Comment by CorruptedArk** [comment]
Fixes merged and applied to multiplayer
