### ISSUE TITLE
[Sugestion] Make logo graphic color match board color

### ISSUE THREAD

**Issue by Vulldozer** [CorruptedArk/open-chaos-chess#39]
**Describe the issue**
The Open Chaos Chess logo in the main menu and in the achievement menu always have red and black board colors.
This is completely fine when using default colors, but can ruin the color scheme when the buttons and logo use different colors.

**To Reproduce**
1. Go to options menu.
2. Change board color 1 to anything other than default
3. See main menu.

**Expected behavior**
The graphic should change color so the board colors ingame and in main menu stay the same.

**Screenshots**
![Screenshot_20210426-122136_Open Chaos Chess.jpg](https://user-images.githubusercontent.com/59207724/116061902-10a7d980-a68c-11eb-8841-8a509fbfc88d.jpg)
**Smartphone**
 - Device: Galaxy Note 8
 - OS: Android 9.0
 - Version: 1.9.0
 - Build Location: CorruptedArk's GitHub release

**Additional context**
This isn't a bug, more a suggestion, nor is it a high priority issue.

**Comment by CorruptedArk** [comment]
@egorguslyan resolved this issue in #40
