### ISSUE TITLE
Choose if you want to play first or second

### ISSUE THREAD

**Issue by Vulldozer** [CorruptedArk/open-chaos-chess#44]
Feature Request

**Is your feature request related to a problem? Please describe.**
You can't choose if you want to start first or let the computer start first

**Describe the solution you'd like**
Either a setting in the options menu or a popup before starting a new game that asks you if you want to make the first move or not.

**Comment by CorruptedArk** [comment]
This should be fairly easy to add in. I think I'll just add a toggle in the settings menu for it

**Comment by Vulldozer** [comment]
Feature was added in the latest update (v1.9.3) and as such I am closing the issue, great work btw

**Comment by CorruptedArk** [comment]
Thanks, I forgot to close the issue myself, and I appreciate the praise
