### ISSUE TITLE
Doubled piece

### ISSUE THREAD

**Issue by egorguslyan** [CorruptedArk/open-chaos-chess#46]
**Description**
If computer moves first and player spams New Game button, piece can copy yourself and computer makes a lot of moves.

**To Reproduce**
1. Go to Settings and let computer move first.
2. Spam New Game button.
3. See crash or game bug.

**Unexpected behavior**
Player don't need to capture all computer pieces to win.
![Screenshot_20210605-134135_Open_Chaos_Chess](https://user-images.githubusercontent.com/42677093/120889288-debf5680-c5eb-11eb-9aa6-83d623192169.png)

**Additional context**
Maybe it's better to place somewhere "Let computer start game" button instead new setting?

**Comment by CorruptedArk** [comment]
Good catch, and I believe I know how to fix this issue already. I should've made the player wait for the computer to finish moving before starting a new game.

**Comment by egorguslyan** [comment]
But this bug is pretty cool. As described in #15 computer gets extra moves and pieces.

**Comment by CorruptedArk** [comment]
That's true, it is cool, but I can't leave it in because of performance issues and whatnot. Also, the smart computer mode you added is already very difficult to beat. I don't think I've been able to beat it once
