### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by LibreHacker** [CorruptedArk/open-chaos-chess#5]
I can make Russian translation

**Comment by CorruptedArk** [comment]
That sounds great, feel free to submit a pull request with translations

**Comment by LibreHacker** [comment]
First commit already.

https://github.com/CorruptedArk/open-chaos-chess/pull/6

I don't know about tech realize localization support.

**Comment by CorruptedArk** [comment]
I merged the pull request. Thanks again!

**Comment by LibreHacker** [comment]
Later i'm done it full.

Nice to see it very soon in next release (:
