### ISSUE TITLE
Feature request: a piece must hit if it can hit

### ISSUE THREAD

**Issue by czarkoff** [CorruptedArk/open-chaos-chess#7]
It would be nice if there was a mode where a piece that can remove opponent's piece would necessarily do so if played.  If there is a choice of pieces to hit,  this choice should still be made by RNG.

Sorry if suggestions are not welcome.

**Comment by CorruptedArk** [comment]
Suggestions are welcome, so thank you for your feedback. I don't think it would be excessively difficult to implement that feature, so it's definitely something I'll look into. Pull requests are welcome as well.

**Comment by CorruptedArk** [comment]
I have now implemented the requested feature. It will be included in v1.6.0 release.
